### ISSUE TITLE
languages

### ISSUE THREAD

**Issue by ser** [QuantiusBenignus/BlahST#1]
Hello that's me again, your favourite issue creator 🥇 

I think that an important thing is missing in the script and documentation, related to multiple languages which can be used for inference.

I made few experiments with switches to URI, and for example:
```
       -F language="pl" \
       -F translate="true" \
```
translates automatically text said in Polish to English, and
```
       -F language="pl" \
       -F translate="false" \
```
gives untranslated text in Polish.

Then there could be for example two keyboard shortcuts defined, each for different results.

**Comment by QuantiusBenignus** [comment]
I see no issue with having issues created when needed. 
There is certainly a lot of functionality exposed in the whisper.cpp executables and it should not be shielded.
I will implement a pass-through, so one can use the command line flags of those directly.

But on the issue with languages, I will split the app in two and have a dedicated multi-lingual script.
The reason is the server, which for english works wonders even with the base.en model, so I do not want to abandon that low-resource solution and will have that model loaded for users who use English only. The wsi script will therefore do just that.

The server can switch models on the fly, but that slows it down and it looses its main advantage to the 'main' executable. Therefore, a multi-lingual wsiml will be created to be used with at least ggml-small.bin for multi-lingual applications.
Users who need multi-lingual support, can use that with the server having preloaded a multi-lingual model. 
Will be committing these changes soon after some tests.

**Comment by QuantiusBenignus** [comment]
OK @ser, the changes are made to add the requested functionality. Docs updated too.
To maintain reasonable quality, I would recommend running the server with a larger, (no. en) model if using other than just English speech input. Of course then the speed of transcription will not be 90x real time anymore. 
There are timestamps echoed throughout the wsiml script that you can uncomment to see what is the timing of the calls with the various models. 
In principle, an API call can be assembled in the shell script to parse and pass through any other whisper runtime parameters to the server, but that is more work and those parameters are for experimentation anyway. You can however, pass all of them through in the calls to the main executable, without the `-n` flag, e.g. `wsiml -l ru -t --best-of 7`

**Comment by ser** [comment]
It looks really good! I think even: perfect! Thanks a lot!!
