### ISSUE TITLE
script

### ISSUE THREAD

**Issue by Fuckingnameless** [QuantiusBenignus/BlahST#3]
there's some problem with this script or insttructions it does not offer to download the whisperfile, neither adds the scripts directory to $PATH, or runs correctly(i manually added the whisperfile path to the scripts)

`.local/bin/wsi -w: cannot execute: required file not found
`

installation output

```
~/Projects/BlahST$ bash install-wsi 


Checking for $HOME/.local/bin...
Copying the orchestrator script(s) to /home/user/.local/bin...
Speech processor scripts copied and made executable. $PATH updated.

Checking for sox...   OK
 
You can use a local whisper.cpp installation, or connect to a whisper.cpp server.
If you have a portable whisperfile instead of whisper.cpp, answer 'n' to the next question.
Do you want to use a local whisper.cpp preinstalled on this machine? [Y/n]: 
n
 
Will be calling a network instance of whisper.cpp for transcription...
Checking for tools needed for network transcription...
Checking for curl...   OK
As a final step, please, set up the server and adjust its IP and port number in the CONFIGURATION block of wsi and/or wsiml.
Installation complete. Run the 'wsi' and/or 'wsiml' scripts from the command line first to verify correct operation.
~/Projects/BlahST$ $PATH
bash: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin: No such file or directory

```

i do have a different package wl-clipboard instead of wl-copy bc that's what's available on linux mint, but the output "a file is not found" is too vague

**Comment by QuantiusBenignus** [comment]
True, the install script is somewhat behind the extra features added over time. Will rework it when I have time. 

For the time being, the logic is that if you select to not search for a compiled whisper.cpp, it is for now assumed that a whisperfile is available in the path (I could have used wget in the script to pull in a whsperfile, but that is a moving target and a matter of choice since there are many options). Check the Config section of each script that you are planning to use to set the correct filename (or complete path to it) of the whisperfile (e.g. whisper.tiny.en.llamafile) so that the script finds it in the PATH. You have to then use the script with -w flag to indicate that you will use the whisperfile, otherwise it will try to fallback to a local whisper.cpp installation that you do not have.

If you are using different Clipboard program, go into the script and replace the wl-copy call with the correct call to your specific program, but I think wl-clipboard is the parent package of wl-copy so you should be good. Test in the terminal to confirm `wl-copy Hello clipboard` and see if you can paste that text w ctrl+v.

Let me know if you need additional help.

QB

**Comment by QuantiusBenignus** [comment]
OK, nice, so assuming you have xsel (for the X11 clipboard) when you issue a command 
```
wsi -c -w 

```

what do you get?

Don't forget that you can partition the problem further, check your /dev/shm folder for example and see if you have a file called `wfile` . That is a wav file so you can use it to test your whisperfile installation:

```
whisper-small.llamafile -f /dev/shm/wfile
```

**Comment by QuantiusBenignus** [comment]
Btw don't run the script in a new shell, run it in the existing shell environment:
'/home/user/.local/bin/wsi -w -c'
(the c is to use the ctrl+v to paste)

It seems your program may be running OK if it is exiting (but it seems you have not set your hotkeys yet). 
So set the mic level to such that the program will exit.

Then go to a window with a text input field and press ctrl+v. It should paste what you said.

**Comment by QuantiusBenignus** [comment]
Remember that this is made to work from the desktop , not in a terminal, i.e. you just press a global keyboard shortcut (hotkey), it transcribes in the background and either you paste the transcribed text anywhere, or it autopastes it. 

The first run in the terminal is to check that it does not complain. If you would like, you can uncomment  some of the echo statements in the script to monitor the output in the terminal. Later , when all is good, comment them back.

**Comment by QuantiusBenignus** [comment]
Yes you can. 
Please, read the Summary and Tips and Tricks sections in the README to get a better idea how it works and to adjust things.
Once you set the global keyboard shortcut for the stop recording command `pkill --signal 2 rec', the sensitivity won't matter since you will be stoping it when needed with the key press. Let me know if you need help setting the hotkeys, I don't have Cinnamon but it should be in the system keyboard settings menu.

**Comment by QuantiusBenignus** [comment]
The whisperfile is using basic, but universal CUDA BLASS implementation (tinyblass) so not as effective as compiled whisper.cpp. Best is compiled whisper.cpp server (I get ~90x real time transcription speed). You can read the whisperfile docs , I think they have a `--recompile` flag that will attempt to recompile CUDA support for the APE and will get a speedup potentially.

**Comment by QuantiusBenignus** [comment]
Once you are happy with the speed and optimizations, feel free to change `AUTOPASTE=true` in the CONFIG block to have the transcribed speech pasted automatically in any window that has the keyboard input focus as soon as it is transcribed (no need for ctrl+v).  Will require xdotool then.

**Comment by QuantiusBenignus** [comment]
Glad you like it, also try the wsiAI later, which will need a local llama.cpp or llamafile.
Let me know if you have any other issues or questions.
Cheers,

QB

**Comment by QuantiusBenignus** [comment]
Closing issue.
